__include__: [
    './dase_dfine_n.yml',
    '../base/deim.yml'
]

output_dir: ./runs/ASW_DETR/deim_dfine

optimizer:
  type: AdamW
  params:
    -
      params: '^(?=.*backbone)(?!.*norm|bn).*$'
      lr: 0.00005
    -
      params: '^(?=.*backbone)(?=.*norm|bn).*$'
      lr: 0.00005
      weight_decay: 0.
    -
      params: '^(?=.*(?:encoder|decoder))(?=.*(?:norm|bn|bias)).*$'
      weight_decay: 0.

  lr: 0.0001
  betas: [0.9, 0.999]
  weight_decay: 0.0001


# Increase to search for the optimal ema
epoches: 132 # 120 + 4n

## Our LR-Scheduler
flat_epoch: 64    # 4 + epoch // 2, e.g., 40 = 4 + 72 / 2
lr_gamma: 1.0
no_aug_epoch: 12

## Our DataAug
train_dataloader: 
  dataset: 
    transforms:
      policy:
        epoch: [4, 64, 120]   # list 

  collate_fn:
    mixup_epochs: [4, 64]
    stop_epoch: 120