__include__: [
  '../dataset.yml',
  '../runtime.yml',
  '../base/dataloader.yml',
  '../base/rt_optimizer.yml',
  '../base/rtdetrv2_hgnetv2.yml',
]


output_dir: ./runs/rtdetr_hgnetv2_n

DEIM: 
  backbone: HGNetv2


HGNetv2:
  name: 'B0'
  return_idx: [1, 2, 3]
  freeze_at: -1
  freeze_norm: False
  use_lab: True


HybridEncoder:
  in_channels: [256, 512, 1024]
  feat_strides: [8, 16, 32]

  # intra
  hidden_dim: 128
  use_encoder_idx: [2]
  dim_feedforward: 512

  # cross
  expansion: 0.34
  depth_mult: 0.5


RTDETRTransformerv2:
  feat_channels: [128, 128, 128]
  feat_strides: [8, 16, 32]
  hidden_dim: 128
  dim_feedforward: 512
  num_levels: 3

  num_layers: 3
  eval_idx: -1

  num_points: [3, 6, 3]


optimizer:
  type: AdamW
  params:
    - 
      params: '^(?=.*(?:norm|bn)).*$'
      weight_decay: 0.


# Increase to search for the optimal ema
epoches: 132 # 148 + 4n
train_dataloader:
  total_batch_size: 8
  dataset:
    transforms:
      policy:
        epoch: 120
  collate_fn:
    stop_epoch: 120
    ema_restart_decay: 0.9999
    base_size_repeat: ~

val_dataloader:
  total_batch_size: 8