task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 4
remap_mscoco_category: False

train_dataloader: 
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/xiao/Models/DEIM/DATA/RSOD/train
    ann_file: /home/xiao/Models/DEIM/DATA/RSOD/annotations/train_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True 
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset: 
    type: CocoDetection
    img_folder: /home/xiao/Models/DEIM/DATA/RSOD/val
    ann_file: /home/xiao/Models/DEIM/DATA/RSOD/annotations/val_coco.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~ 
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction